// petfeliz-frontend/src/components/Footer/Footer.vue
<template>
      <footer class="footerContainer">
         <nav>
            <p class="titleSection">Links úteis</p>
            <ul>
               <li>
                  <router-link to="/">
                     <a>Início</a>
                  </router-link>
               </li>
               <li>
                  <router-link to="/">
                     <a>Produtos</a>
                  </router-link>
               </li>
               <li>
                  <router-link to="/">
                     <a>Destaques</a>
                  </router-link>
               </li>
               <li>
                  <router-link to="/">
                     <a>Sobre nós</a>
                  </router-link>
               </li>
               <li>
                  <router-link to="/">
                     <a>Contato</a>
                  </router-link>
               </li>
            </ul>
         </nav>
         <div class="centerContainer">
            <p>PetFeliz LTDA.</p> © 2021. All Rights Reserved
         </div>
         <div class="rightSideContainer">
            <div>
               <p>Redes Sociais</p>
               <div>
                  <router-link to="/">
                     <img
                        src="/facebook.svg"
                        width="30"
                        height="30"
                        alt="Facebook"
                     />
                  </router-link>
                  <router-link to="/" class="centerSocialLogo">
                     <img
                        src="/instagram.svg"
                        width="30"
                        height="30"
                        alt="Instagram"
                     />
                  </router-link>
                  <router-link to="/">
                     <img
                        src="/whatsapp.svg"
                        width="30"
                        height="30"
                        alt="Whatsapp"
                     />
                  </router-link>
               </div>
            </div>
         </div>
      </footer>
</template>

<style lang="scss">
   @import "Footer.scss";
</style>

// src/components/Footer/Footer.tsx
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";

import styles from "./styles.module.scss";

export function Footer() {

   return (
      <footer className={styles.footerContainer}>
         <nav>
            <p className={styles.titleSection}>Links úteis</p>
            <ul>
               <li>
                  <Link href="/">
                     <a>Início</a>
                  </Link>
               </li>
               <li>
                  <Link href="/catalog">
                     <a>Categorias</a>
                  </Link>
               </li>
               <li>
                  <Link href="/notReady">
                     <a>Promoções</a>
                  </Link>
               </li>
               <li>
                  <Link href="/notReady">
                     <a>Sobre nós</a>
                  </Link>
               </li>
               <li>
                  <Link href="/notReady">
                     <a>Contato</a>
                  </Link>
               </li>
            </ul>
         </nav>
         <div className={styles.centerContainer}>
            <p>PetFeliz LTDA.</p> © 2021. All Rights Reserved
         </div>
         <div className={styles.rightSideContainer}>
            <div className={styles.container}>
               <p>Redes Sociais</p>
               <div>
                  <Link href="/notReady" passHref={true}>
                     <img
                        src="/facebook.svg"
                        width="30"
                        height="30"
                        alt="Facebook"
                     />
                  </Link>
                  <Link href="/notReady" passHref={true}>
                     <img
                        src="/instagram.svg"
                        width="30"
                        height="30"
                        alt="Instagram"
                     />
                  </Link>
                  <Link href="/notReady" passHref={true}>
                     <img
                        src="/whatsapp.svg"
                        width="30"
                        height="30"
                        alt="Whatsapp"
                     />
                  </Link>
               </div>
            </div>
         </div>
      </footer>
   );
}
